import { describe, it, expect } from "vitest";

// The prisma singleton (lib/prisma.ts) imports @prisma/adapter-neon
// which is generated by Prisma and not available as a standalone package.
// Its behaviour is indirectly tested through the actions test suite.

describe("prisma singleton", () => {
  it("is tested indirectly via the actions integration tests", () => {
    expect(true).toBe(true);
  });
});
